catalogHost="catalog"
cartHost="cart"
recommendHost="recommendation"
currencyHost="currency"
shippingHost="shipping"
checkoutHost="checkout"
adHost="ads"

[ballerina.observe]
tracingEnabled=true
tracingProvider="jaeger"

[ballerinax.jaeger]
agentHostname="jaeger"
agentPort=55680
samplerType="const"
samplerParam=1.0
reporterFlushInterval=2000
reporterBufferSize=1000
