[package]
org = "wso2"
name = "shippingservice"
version = "0.1.0"
distribution = "2201.2.3"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "wso2"
name = "client_stubs"
version = "0.1.0"
repository = "local"
